In [ ]:
# Problem 1: 
# Create a 3x3 matrix with values ranging from 0 to 8

In [2]:
import numpy as np
arr =np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Problem 2: 
# Find the sum of all the elements in a NumPy array

In [4]:
import numpy as np
arr=np.arange(9).reshape(3,3)
result=np.sum(arr)
print(result)

36


In [ ]:
# Problem 3: 
# Replace all odd numbers in an array with -1

In [6]:
import numpy as np
arr=np.arange(10,19).reshape(3,3)
odd_number= arr % 2 != 0
arr[odd_number]=-1
print(arr)

[[10 -1 12]
 [-1 14 -1]
 [16 -1 18]]


In [ ]:
# Problem 4: 
# How to get the common items between two python NumPy arrays?

In [14]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=np.array([11,12,13,4,5])
common=np.intersect1d(arr,arr1)
print(common)


[4 5]


In [ ]:
# Problem 5: 
# How to get the positions where elements of two arrays match?

In [17]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr1=np.array([11,12,13,4,5])
common=np.where(arr==arr1)[0]
print(common)

[3 4]


In [ ]:
# Problem 6: 
# How to create a 2D array containing random floats between 5 and 10?

In [21]:
import numpy as np
arr=np.random.uniform(5,10 ,size=(3,4))
print(arr)

[[9.64339633 6.80012149 5.01955036 7.67193579]
 [7.01444624 9.27697682 7.31520382 9.91738287]
 [6.09633184 5.99320402 6.32605478 6.84938393]]


In [ ]:
# Problem 7: 
# Subtract the mean of each row of a matrix

In [1]:
import numpy as np


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


row_means = np.mean(matrix, axis=1)


result_matrix = matrix - row_means[:, np.newaxis]

print("Original Matrix:")
print(matrix)
print("\nMean of each row:")
print(row_means)
print("\nResult after subtracting mean of each row:")
print(result_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean of each row:
[2. 5. 8.]

Result after subtracting mean of each row:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [5]:
import numpy as np
arr=np .array([[1,2,3],
              [4,5,6],
              [8,9,10]])

row_mean=np.mean(arr , axis=1)
sub_by_row =arr - row_mean[: ,np.newaxis]
print("Original Matrix:")
print(arr)
print("\nMean of each row:")
print(row_mean)
print("\nResult after subtracting mean of each row:")
print(sub_by_row)

Original Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]

Mean of each row:
[2. 5. 9.]

Result after subtracting mean of each row:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [ ]:
# Problem 8: 
# How to sort an array by the nth column?

In [12]:
import numpy as np
arr=np.array([[5,2,6],
             [3,6,9],
             [4,9,1]])
n=1
col_sort=np.argsort(arr[: , n])
sort_arr=np.sort(arr)
print(sort_arr)

[[2 5 6]
 [3 6 9]
 [1 4 9]]


In [8]:
import numpy as np

# Example array
array = np.array([[1, 4, 7],
                  [3, 6, 9],
                  [2, 5, 8]])

n = 1

sorted_indices = np.argsort(array[:, n])


sorted_array = array[sorted_indices]

print("Original Array:")
print(array)
print("\nSorted Array by the nth column:")
print(sorted_array)


Original Array:
[[1 4 7]
 [3 6 9]
 [2 5 8]]

Sorted Array by the nth column:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# Problem 9: 
# How to tell if a given 2D array has null columns?

In [4]:
def has_null_columns(arr):
    if not arr:
        return False  

    num_rows = len(arr)
    num_cols = len(arr[0])

    for col in range(num_cols):
        column_empty = True
        for row in range(num_rows):
            if arr[row][col]:
                column_empty = False
                break
        if column_empty:
            return True

    return False


array_with_null_columns = [
    [1, None, 3],
    [None, None, None],
    [4, None, 6]
]

array_without_null_columns = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(has_null_columns(array_with_null_columns)) 
print(has_null_columns(array_without_null_columns))  


True
False


In [ ]:
# Problem 10: 
# Find the nearest value from a given value in an array

In [5]:
def find_nearest_value(arr, target):
    nearest_value = None
    min_difference = float('inf')

    for value in arr:
        difference = abs(value - target)
        if difference < min_difference:
            min_difference = difference
            nearest_value = value

    return nearest_value

# Example usage:
arr = [1, 3, 5, 7, 9]
target = 6
nearest = find_nearest_value(arr, target)
print("Nearest value to", target, "in the array is:", nearest)


Nearest value to 6 in the array is: 5


In [ ]:
# Problem 11: 
# Create an array class that has a name attribute

In [9]:
class NamedArray:
    def __init__(self, name, elements):
        self.name = name
        self.elements = elements

    def __str__(self):
        return f"{self.name}: {self.elements}"

    def __repr__(self):
        return f"NamedArray('{self.name}', {self.elements})"

# Example usage:
arr = NamedArray("Example Array", [1, 2, 3, 4, 5])
print(arr)  
print(arr.name)  
print(arr.elements)  


Example Array: [1, 2, 3, 4, 5]
Example Array
[1, 2, 3, 4, 5]


In [ ]:
# Problem 12: 
# Find the diagonal of a dot product

In [10]:
import numpy as np

def diagonal_of_dot_product(matrix1, matrix2):
    dot_product = np.dot(matrix1, matrix2)
    diagonal = np.diagonal(dot_product)
    return diagonal

# Example usage:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

diagonal_result = diagonal_of_dot_product(matrix1, matrix2)
print("Diagonal of the dot product:", diagonal_result)


Diagonal of the dot product: [19 50]


In [ ]:
# Problem 13: 
# Compute the rank of a matrix

In [11]:
import numpy as np

def compute_matrix_rank(matrix):
    rank = np.linalg.matrix_rank(matrix)
    return rank

# Example usage:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rank = compute_matrix_rank(matrix)
print("Rank of the matrix:", rank)


Rank of the matrix: 2


In [ ]:
# Problem 14: 
# Find the most frequent value in an array

In [12]:
from collections import Counter

def most_frequent_value(arr):
    if not arr:
        return None  
    
    
    counts = Counter(arr)
    

    most_common = counts.most_common(1)  
    most_frequent_value = most_common[0][0]
    
    return most_frequent_value


array = [1, 3, 5, 3, 2, 1, 3, 3, 2, 3]

result = most_frequent_value(array)
print("The most frequent value in the array is:", result)


The most frequent value in the array is: 3


In [ ]:
# Problem 15: 
# Create a checkerboard 8x8 matrix using the NumPy `tile` function, where the tiles alternate between 0 and 1. 
# The matrix should start with 1 in the top-left corner.

In [13]:
import numpy as np


checkerboard_tile = np.array([[1, 0],
                              [0, 1]])

checkerboard_matrix = np.tile(checkerboard_tile, (4, 4))

print("Checkerboard 8x8 matrix:")
print(checkerboard_matrix)


Checkerboard 8x8 matrix:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
# Problem 16: 
# Calculate the eigenvalues and eigenvectors of a given 3x3 matrix. 
# Use a static 3x3 matrix for the example.

In [14]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]

Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
# Problem 17: 
# How to get the n largest values of an array?

In [15]:
import numpy as np

def get_n_largest(arr, n):
    
    partitioned = np.partition(arr, -n)
    
    
    nth_largest = partitioned[-n:]
    
    return nth_largest


array = np.array([4, 2, 9, 5, 1, 6, 3, 8, 7])
n = 3

result = get_n_largest(array, n)
print(f"The {n} largest values in the array are:", result)


The 3 largest values in the array are: [7 8 9]


In [ ]:
# Problem 18: 
# Replace NaNs with the median of the array

In [16]:
import numpy as np

def replace_nans_with_median(arr):
    
    median = np.nanmedian(arr)
    
    
    arr[np.isnan(arr)] = median
    
    return arr


array = np.array([1, 2, np.nan, 4, 5, np.nan, 7, 8, 9])
array_with_nans_replaced = replace_nans_with_median(array)

print("Array with NaNs replaced by median:", array_with_nans_replaced)


Array with NaNs replaced by median: [1. 2. 5. 4. 5. 5. 7. 8. 9.]


In [ ]:
# Problem 19: 
# How to find the closest value (to a given scalar) in a vector?

In [17]:
import numpy as np

def find_closest_value(vector, scalar):
    
    differences = np.abs(vector - scalar)
    

    closest_index = np.argmin(differences)
    
    
    closest_value = vector[closest_index]
    
    return closest_value

vector = np.array([1, 3, 5, 7, 9])
scalar = 6

closest_value = find_closest_value(vector, scalar)
print("Closest value to", scalar, "in the vector:", closest_value)


Closest value to 6 in the vector: 5


In [ ]:
# Problem 20: 
# How to convert a float (32 bits) array into an integer (32 bits) in place?


In [9]:

float_array = [3.14, 2.718, 1.618]


for i in range(len(float_array)):
    float_array[i] = int(float_array[i])


print(float_array)


[3, 2, 1]
