## Set 1

In [1]:
# Check if a number n is a power of 2 using bitwise operator.

# Explanation:
    # If and operation of n and n-1 is equals to zero,  the number is a power of 2
    #      n = 8 = 1000
    #    n-1 = 7 = 0111
    #  n & (n-1) = 0000 = 0

# Solution:
def powerOf2(n):
    return n != 2 and (n &(n-1)) == 0

n = int(input('Enter a number:'))

if powerOf2(n):
    print('Yes!', n, 'is a power of 2')
else:
    print('No!', n, 'is not a power of 2')

No! 5 is not a power of 2


In [2]:
# Without using the division operator /, divide a number by 2

# Explanation:
    # To divde a number by 2, right shift its binary equivalent by 1 bit. The result is the number divided by 2
    #   n = 8 = 1000
    #  n >> 1 = 0100
    #  n = 0100 = 4
# It performs floor division

def divideBy2(n):
    return n>>1

n = int(input('Enter a number:'))
print(n,'divided by 2 using bitwise operator is',divideBy2(n))

6 divided by 2 using bitwise operator is 3


In [3]:
# Implement a bitwise operator XOR on two boolean values x and y
#  XOR: 
#     If two bits are same, it return 0 
#     If two bits are different, it returns 1
#  x = 3 = 011
#  y = 5 = 101
#  x ^ y = 110 = 6
def XOR(x, y):
    return x^y

x = int(input('x='))  
y = int(input('y='))  

print(x,'XOR', y, 'is', XOR(x, y))

4 XOR 5 is 1


In [4]:
# Using logical operators, check if a string is non-empty and starts with an uppercase
# Explanation: 
# to check non-empty: bool(string)
# to check if it starts with upper-case letter: string[0].isupper()

# Solution:
def stringCheck(string):
    return not bool(string) and string[0].isupper()

string = input('Enter a string')
if stringCheck(string):
    print('String is non-empty and starts with an upper-case letter')
else:
    print('String is either empty or does not start with upper-case letter')

String is either empty or does not start with upper-case letter


In [8]:
# Determine if two float numbers are approximately equal(within 0.001)
# Explanation: Check if absolute difference of two numbers is less than 0.001
# Solution:
def approximatelyEqual(x, y):
    return abs(x-y) < 0.001
x = float(input('x='))
y = float(input('y='))

if approximatelyEqual(x, y):
    print(x, 'and', y, 'are approximately equal')
else:
    print(x, 'and', y, 'are not approximately equal')

7.006 and 7.007 are approximately equal


In [12]:
# Swap two numbers a and b using bitwise operator
# Explanation: use XOR operation
# Solution:
def swapNumbers(a, b):
    a = a ^b
    b = a ^ b
    a = a ^ b
    return a, b

a = int(input('a='))
b = int(input('b='))

print('Before swapping: ', a, ',', b)
a, b = swapNumbers(a, b)
print('After swapping:  ', a, ',', b)

Before swapping:  4 , 6
After swapping:   6 , 4


In [28]:
# Reverse the bits of a 32-bit unsigned integer n
# Explanation: First, fill the number upto 32-bits and then reverse the string
# Solution:
def reverse32bitnumber(n):
    return (''.join(reversed(bin(n)[2:].zfill(32))))

n = int(input('Enter a number:'))
print(n, 'is',bin(n)[2:].zfill(32))
print(n, 'reversed is:', reverse32bitnumber(n))

23 is 00000000000000000000000000010111
23 reversed is: 11101000000000000000000000000000


In [31]:
# Using bitwise operators, detrmine if an integer is odd
# Explanation:
# If last digit of binary representation of a number is 1, it is odd
# Perform bitwise and on n and 1
# Solution:
def oddEve(n):
    return n & 1

n = int(input('n='))
if oddEve(n) == 1:
    print(n, 'is odd')
else:
    print(n, 'is even')

5 is odd


In [32]:
# Check if a number n is within 10 units of 100 using a single expression
# Explanation: It means the number should be 10 units above or below 100
# Solution:
def within10units(n):
    return abs(n-100) <= 10

n = int(input('Enter a number:'))
if within10units(n):
    print('Yes!', n, 'is within 10 units of 100')
else:
    print('No!', n, 'is not within 10 units of 100')


Yes! 110 is within 10 units of 100


In [33]:
# Without using **, calculate the cube of a number x
# Explanation: multiply x with itself 3 times
# Solution:
x = int(input('Enter a number:'))
print('Cube of', x, 'is', x*x*x)

Cube of 4 is 64


## Set 2

In [1]:
#  Calculate the remainder of 1234 divided by [100 without using the % operator.
# Explanation:
# Dividend = Divisor * Quotient + Remainder
# Remainder = Dividend - (Divisor * Quotient)
# Solution:
def remainder(Dividend = 1234, Divisor = 100):
    Quotient = Dividend // Divisor
    Remainder = Dividend - (Divisor * Quotient)
    return Remainder

print(remainder())

34


In [3]:
# Reverse the bits of an 8-bit binary number, 0b11010100
n = '0b11010100'
reversed_number = ''.join(reversed(n[2:]))
print('Reversed number for',n[2:], 'is', reversed_number)

Reversed number for 11010100 is 00101011


In [6]:
# Check if two numbers, a = 4 and b = 9, have opposite signs using bitwise operators.
# Explanation:
# If XOR of two numbers is less than 0, then the numbers are of opposite sign
# Solution:
def oppositeSign(a = 4, b = 9):
    return a^b < 0

if oppositeSign():
    print('The numbers have opposite signs')
else:
    print('The numbers have same sign')

The numbers have same sign


In [9]:
# Swap two integers a = 3 and b = 5 without using extra space.
def swapNumbers(a, b):
    a = a ^ b
    b = a ^ b
    a = a ^ b
    return [a,b]
a = 3
b = 5
print('Before swapping:', [a,b])
print('After swapping: ', swapNumbers(a,b))

Before swapping: [3, 5]
After swapping:  [5, 3]


In [11]:
# Determine if an integer n is a power of two without using loops or recursion.
def powerOf2(n):
    return n != 0 and (n & (n-1)) == 0

n = int(input('Enter a  number:'))
if powerOf2(n):
    print('Yes!', n, 'is a power of 2')
else:
    print('No!', n, 'is not a power of 2')

Yes! 4 is a power of 2


In [1]:
import numpy as np 

In [6]:
a = np.array([[1,2,3,4,5], [4,5,6,7,8]], ndmin=4)
print(a)

[[[[1 2 3 4 5]
   [4 5 6 7 8]]]]


In [7]:
a = np.array([1,2,3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [8]:
a = np.array([1,2,3])
print(a)
print('\n')

b = np.array([[1,3,6],[2,4,8]])
print(b)
print(b.shape)
print(b.size)
print('\n')

[1 2 3]


[[1 3 6]
 [2 4 8]]
(2, 3)
6




In [11]:
c = np.array([1,2,3,4,5], dtype=int)
print(c)
print(c.itemsize)
print(c.dtype.name)

[1 2 3 4 5]
4
int32


In [15]:
d = np.arange(16).reshape(2,4,2)
print(d)
print(type(d))

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
<class 'numpy.ndarray'>
